environment:
  - "PGDATA=devsupport/db"
processes:
  elm-live:
    command: "elm-live src/Main.elm --verbose --pushstate --dir dist/ --start-page html/index.html -- --output=dist/js/main.js"
    working_dir: frontend/
  ccs-watch:
    command: watchexec -w dist/css touch src/Main.elm
    working_dir: frontend/
  database:
    command: "devsupport/run_postgres.sh"
